language: go

go:
    - 1.3

services:
    - redis-server
    - elasticsearch

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpcap-dev

install:
    - make deps
    - make

script: make testlong

notifications:
    email:
        - dev@packetbeat.com
