language: go

go:
    - 1.4

sudo: false

services:
    - redis-server
    - elasticsearch

addons:
  apt:
    packages:
      - libpcap-dev
      - python-virtualenv
      - geoip-database

before_install:
    - ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/packetbeat

install:
    - make

script: make testlong

notifications:
    email:
        - tudor@elastic.co
        - monica@elastic.co
