language: go

go:
  - 1.5

sudo: false

addons:
  apt:
    packages:
      - libpcap-dev
      - python-virtualenv
      - geoip-database

before_install:
  # Redo the travis setup but with the elastic/packetbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/elastic/packetbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/elastic/packetbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/elastic/packetbeat
  - cd $HOME/gopath/src/github.com/elastic/packetbeat

install:
  - make

script:
  - make full-coverage

notifications:
    email:
        - tudor@elastic.co
        - monica@elastic.co

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/full.cov