language: go

go:
    - 1.4

services:
    - redis-server
    - elasticsearch

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libpcap-dev python-virtualenv geoip-database

install:
    - make deps
    - make

script: make testlong

notifications:
    email:
        - dev@packetbeat.com
