libbeat:
  build: .
  links:
    - redis
    - elasticsearch-172
    - elasticsearch-200
    - logstash
  environment:
    - ES_HOST=elasticsearch-172
    - ES_PORT=9200
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - LS_HOST=logstash
    - LS_LUMBERJACK_TCP_PORT=12345
elasticsearch-172:
  image: elasticsearch:1.7.2
elasticsearch-200:
  image: elasticsearch:2.0.0-beta2
  command: elasticsearch -Des.network.host=0.0.0.0
redis:
  image: redis
logstash:
  build: docker/logstash
  environment:
    - ES_HOST=elasticsearch-172
    - ES_PORT=9200
  links:
    - elasticsearch-172
