libbeat:
  build: .
  links:
    - redis
    - elasticsearch
  environment:
    - ES_HOST=elasticsearch
    - ES_PORT=9200
    - REDIS_HOST=redis
    - REDIS_PORT=6379
elasticsearch:
  image: elasticsearch
redis:
  image: redis
